import re
import logging
import pandas as pd
import numpy as np
from typing import Dict, Any, List, Optional

logger = logging.getLogger(__name__)

class DataCleanerError(Exception):
    """Custom exception raised when data cleaning fails."""
    pass

MISSING_VALUE_STRINGS = {
    "", " ", "na", "n/a", "null", "none", "-", "nan", "<na>", "nullvalue"
}

def clean_dataset(
    df: pd.DataFrame,
    schema: Dict[str, Any],
    profile: Dict[str, Any],
    remove_exact_duplicates: bool = True
) -> Dict[str, Any]:
    """
    Standardizes a Pandas DataFrame into a consistent, clean representation
    based on inferred schema and profiling metadata.

    :param df: Input raw pd.DataFrame
    :param schema: Inferred schema dictionary from schema_inference
    :param profile: Profiling metadata dictionary from data_profiler
    :param remove_exact_duplicates: If True, removes exact duplicate rows
    :return: Standardized Dataset object containing cleaned_df, metadata, updated_schema, profile, and cleaning_report
    :raises DataCleanerError: If inputs are invalid
    """
    if df is None or not isinstance(df, pd.DataFrame):
        logger.error("Data cleaner received invalid df input (not a DataFrame)")
        raise DataCleanerError("Input must be a valid Pandas DataFrame.")

    if schema is None or not isinstance(schema, dict) or "columns" not in schema:
        logger.error("Data cleaner received invalid schema input")
        raise DataCleanerError("Input schema must be a valid dictionary generated by schema_inference.")

    original_row_count = len(df)
    original_column_count = len(df.columns)

    # Work on a copy to prevent accidental mutation of input DataFrame
    cleaned_df = df.copy()

    cleaning_report = {
        "column_renames": [],
        "missing_values_normalized": 0,
        "whitespace_values_cleaned": 0,
        "numeric_conversions": {},
        "date_conversions": {},
        "duplicate_rows_removed": 0,
        "warnings": []
    }

    # 1. Standardize Column Names
    cleaned_df, updated_schema, col_renames = _standardize_column_names(cleaned_df, schema)
    cleaning_report["column_renames"] = col_renames

    # Look up column metadata from updated schema by standardized name
    schema_cols_map = {col["name"]: col for col in updated_schema.get("columns", [])}

    # 2. Whitespace cleaning and missing value normalization
    for col in cleaned_df.columns:
        col_meta = schema_cols_map.get(col, {})
        sem_type = col_meta.get("semantic_type", "unknown")

        # Whitespace cleaning FIRST so " N/A " becomes "N/A" before missing normalization
        if sem_type in ("text", "categorical", "identifier", "unknown") or _is_string_or_object(cleaned_df[col]):
            ws_count = _clean_whitespace_in_col(cleaned_df, col)
            cleaning_report["whitespace_values_cleaned"] += ws_count

        # Missing value normalization SECOND
        norm_count = _normalize_missing_values_in_col(cleaned_df, col)
        cleaning_report["missing_values_normalized"] += norm_count

    # 3. Type-Specific Conversions based on Schema
    for col in cleaned_df.columns:
        col_meta = schema_cols_map.get(col, {})
        sem_type = col_meta.get("semantic_type", "unknown")

        if sem_type == "numeric":
            num_report = _convert_numeric_column(cleaned_df, col)
            cleaning_report["numeric_conversions"][col] = num_report
            if num_report["failed"] > 0:
                cleaning_report["warnings"].append({
                    "column": col,
                    "issue": f"Failed to parse {num_report['failed']} numeric values (set to NaN)"
                })
        elif sem_type == "date":
            date_report = _convert_date_column(cleaned_df, col)
            cleaning_report["date_conversions"][col] = date_report
            if date_report["failed"] > 0:
                cleaning_report["warnings"].append({
                    "column": col,
                    "issue": f"Failed to parse {date_report['failed']} date values (set to NaT)"
                })
        elif sem_type == "boolean":
            _convert_boolean_column(cleaned_df, col)
        elif sem_type == "identifier":
            _preserve_identifier_column(cleaned_df, col)

    # 4. Handle Exact Duplicate Rows
    duplicate_rows_removed = 0
    if remove_exact_duplicates and original_row_count > 0:
        dupes_count = int(cleaned_df.duplicated().sum())
        if dupes_count > 0:
            cleaned_df = cleaned_df.drop_duplicates().reset_index(drop=True)
            duplicate_rows_removed = dupes_count

    cleaning_report["duplicate_rows_removed"] = duplicate_rows_removed
    final_row_count = len(cleaned_df)

    metadata = {
        "original_row_count": original_row_count,
        "final_row_count": final_row_count,
        "column_count": original_column_count,
        "duplicate_rows_removed": duplicate_rows_removed
    }

    result = {
        "data": cleaned_df,
        "metadata": metadata,
        "schema": updated_schema,
        "profile": profile,
        "cleaning_report": cleaning_report
    }

    logger.info(f"Data cleaning completed: Rows {original_row_count} -> {final_row_count}, Columns {original_column_count}")
    return result


def _is_string_or_object(series: pd.Series) -> bool:
    """Helper to check if pandas series is string or object dtype."""
    return pd.api.types.is_string_dtype(series) or pd.api.types.is_object_dtype(series)


def _standardize_column_names(
    df: pd.DataFrame,
    schema: Dict[str, Any]
) -> tuple[pd.DataFrame, Dict[str, Any], List[Dict[str, str]]]:
    """
    Normalizes column names to lowercase snake_case format while maintaining unique names
    and recording original-to-standardized mapping.
    """
    col_renames = []
    new_columns = []
    seen_names: set[str] = set()

    for col in df.columns:
        orig_str = str(col)

        # 1. Lowercase & strip
        s = orig_str.strip().lower()

        # 2. Replace separators (/ - . space) with underscore
        s = re.sub(r"[\s/\-\.\:]+", "_", s)

        # 3. Keep only alphanumeric and underscore
        s = re.sub(r"[^\w_]", "", s)

        # 4. Remove duplicate underscores & trim underscores
        s = re.sub(r"_+", "_", s).strip("_")

        if not s:
            s = "column"

        # 5. Ensure uniqueness
        base_name = s
        counter = 2
        while s in seen_names:
            s = f"{base_name}_{counter}"
            counter += 1

        seen_names.add(s)
        new_columns.append(s)
        col_renames.append({
            "original": orig_str,
            "standardized": s
        })

    df.columns = new_columns

    # Update Schema columns mapping
    orig_to_new = {item["original"]: item["standardized"] for item in col_renames}
    updated_schema = schema.copy()

    updated_cols = []
    for col_meta in schema.get("columns", []):
        c_copy = col_meta.copy()
        orig = c_copy.get("original_name", c_copy.get("name"))
        c_copy["original_name"] = orig
        c_copy["name"] = orig_to_new.get(orig, c_copy.get("name"))
        updated_cols.append(c_copy)

    updated_schema["columns"] = updated_cols
    updated_schema["numeric_columns"] = [orig_to_new.get(c, c) for c in schema.get("numeric_columns", [])]
    updated_schema["categorical_columns"] = [orig_to_new.get(c, c) for c in schema.get("categorical_columns", [])]
    updated_schema["date_columns"] = [orig_to_new.get(c, c) for c in schema.get("date_columns", [])]
    updated_schema["identifier_columns"] = [orig_to_new.get(c, c) for c in schema.get("identifier_columns", [])]
    updated_schema["boolean_columns"] = [orig_to_new.get(c, c) for c in schema.get("boolean_columns", [])]
    updated_schema["text_columns"] = [orig_to_new.get(c, c) for c in schema.get("text_columns", [])]

    return df, updated_schema, col_renames


def _clean_whitespace_in_col(df: pd.DataFrame, col: str) -> int:
    """Strips leading/trailing whitespace from string columns without affecting internal spaces."""
    series = df[col]
    if _is_string_or_object(series):
        non_null_s = series.dropna()
        if len(non_null_s) > 0:
            str_s = non_null_s.astype(str)
            trimmed = str_s.str.strip()
            cleaned_mask = str_s != trimmed
            count = int(cleaned_mask.sum())
            if count > 0:
                res = series.copy()
                res.loc[non_null_s.index] = trimmed
                df[col] = res
                return count
    return 0


def _normalize_missing_values_in_col(df: pd.DataFrame, col: str) -> int:
    """Normalizes string missing representations ('N/A', 'null', '', '-') to np.nan."""
    series = df[col]
    if _is_string_or_object(series):
        str_series = series.astype(str).str.strip()
        mask = str_series.str.lower().isin(MISSING_VALUE_STRINGS)
        norm_count = int(mask.sum())
        if norm_count > 0:
            res = series.mask(mask, np.nan)
            df[col] = res
            return norm_count
    return 0


def _convert_numeric_column(df: pd.DataFrame, col: str) -> Dict[str, int]:
    """Safely converts string numeric columns (handling '$1,200.50', '2,000') to numeric."""
    series = df[col]
    if pd.api.types.is_numeric_dtype(series):
        return {"converted": int(series.notnull().sum()), "failed": 0}

    initial_non_null = int(series.notnull().sum())
    clean_str = series.astype(str).str.replace(r"[\$,\s]", "", regex=True)
    numeric_series = pd.to_numeric(clean_str, errors="coerce")

    new_non_null = int(numeric_series.notnull().sum())
    failed_count = max(0, initial_non_null - new_non_null)

    df[col] = numeric_series
    return {"converted": new_non_null, "failed": failed_count}


def _convert_date_column(df: pd.DataFrame, col: str) -> Dict[str, int]:
    """Converts date column to Pandas datetime, converting invalid dates to NaT."""
    series = df[col]
    if pd.api.types.is_datetime64_any_dtype(series):
        return {"converted": int(series.notnull().sum()), "failed": 0}

    initial_non_null = int(series.notnull().sum())
    dt_series = pd.to_datetime(series, errors="coerce", format="mixed")

    new_non_null = int(dt_series.notnull().sum())
    failed_count = max(0, initial_non_null - new_non_null)

    df[col] = dt_series
    return {"converted": new_non_null, "failed": failed_count}


def _convert_boolean_column(df: pd.DataFrame, col: str) -> None:
    """Normalizes boolean values ('yes'/'no', 'true'/'false', '1'/'0') to boolean."""
    series = df[col]
    if pd.api.types.is_bool_dtype(series):
        return

    mapping = {
        "true": True, "yes": True, "y": True, "1": True, "t": True,
        "false": False, "no": False, "n": False, "0": False, "f": False
    }
    lowered = series.astype(str).str.strip().str.lower()
    df[col] = lowered.map(mapping)


def _preserve_identifier_column(df: pd.DataFrame, col: str) -> None:
    """Preserves identifiers as strings to prevent stripping leading zeros (e.g. '00123')."""
    series = df[col]
    if _is_string_or_object(series):
        non_null = series.notnull()
        str_vals = series[non_null].astype(str)
        res = series.copy()
        res.loc[non_null] = str_vals
        df[col] = res
