import math
import logging
import pandas as pd
import numpy as np
from typing import Dict, Any, List, Optional

logger = logging.getLogger(__name__)

class DataProfilerError(Exception):
    """Custom exception raised when data profiling fails."""
    pass

def profile_dataset(df: pd.DataFrame, schema: Dict[str, Any], top_n: int = 5) -> Dict[str, Any]:
    """
    Profiles a Pandas DataFrame using its inferred schema to measure dataset metrics,
    quality summary, missing values, duplicate counts, and column-level statistics.

    :param df: Input raw pd.DataFrame
    :param schema: Inferred schema dictionary from schema_inference.infer_schema
    :param top_n: Number of top frequency values to report for categorical columns
    :return: Structured JSON-serializable profiling dictionary
    :raises DataProfilerError: If df or schema input is invalid
    """
    if df is None or not isinstance(df, pd.DataFrame):
        logger.error("Data profiler received invalid df input (not a DataFrame)")
        raise DataProfilerError("Input must be a valid Pandas DataFrame.")

    if schema is None or not isinstance(schema, dict) or "columns" not in schema:
        logger.error("Data profiler received invalid schema input")
        raise DataProfilerError("Input schema must be a valid dictionary generated by schema_inference.")

    row_count = len(df)
    column_count = len(df.columns)

    # 1. Dataset-level Duplicate Calculation
    duplicate_row_count = int(df.duplicated().sum()) if row_count > 0 else 0
    duplicate_row_percentage = round((duplicate_row_count / row_count) * 100, 2) if row_count > 0 else 0.0

    columns_profile: List[Dict[str, Any]] = []
    total_missing_values = 0
    columns_with_missing = 0
    columns_with_all_null = 0

    # Look up schema metadata by column name
    schema_cols_map = {col["name"]: col for col in schema.get("columns", [])}

    # 2. Iterate through each column for measurement
    for col in df.columns:
        col_str = str(col)
        series = df[col]
        col_schema = schema_cols_map.get(col_str, {})
        semantic_type = col_schema.get("semantic_type", "unknown")
        dtype_str = str(series.dtype)

        missing_count = int(series.isnull().sum())
        non_null_count = int(series.notnull().sum())
        missing_percentage = round((missing_count / row_count) * 100, 2) if row_count > 0 else 0.0
        unique_count = int(series.nunique(dropna=True))

        uniqueness_ratio = round(unique_count / non_null_count, 4) if non_null_count > 0 else 0.0
        all_null = bool(missing_count == row_count)
        constant = bool(unique_count == 1)

        if missing_count > 0:
            columns_with_missing += 1
            total_missing_values += missing_count

        if all_null:
            columns_with_all_null += 1

        col_prof: Dict[str, Any] = {
            "name": col_str,
            "dtype": dtype_str,
            "semantic_type": semantic_type,
            "row_count": row_count,
            "missing_count": missing_count,
            "missing_percentage": missing_percentage,
            "non_null_count": non_null_count,
            "unique_count": unique_count,
            "uniqueness_ratio": uniqueness_ratio,
            "all_null": all_null,
            "constant": constant
        }

        # 3. Calculate Type-Specific Statistics safely
        try:
            if all_null:
                col_prof["statistics"] = None
            elif semantic_type == "numeric":
                col_prof["statistics"] = _profile_numeric(series)
            elif semantic_type == "categorical":
                col_prof["top_values"] = _profile_categorical(series, top_n=top_n)
            elif semantic_type == "text":
                col_prof["statistics"] = _profile_text(series)
            elif semantic_type == "date":
                col_prof["statistics"] = _profile_date(series)
            elif semantic_type == "identifier":
                col_prof["statistics"] = _profile_identifier(series, unique_count, non_null_count)
            elif semantic_type == "boolean":
                col_prof["top_values"] = _profile_categorical(series, top_n=2)
            else:
                col_prof["statistics"] = None
        except Exception as e:
            logger.warning(f"Error profiling column '{col_str}': {e}")
            col_prof["statistics"] = None

        columns_profile.append(col_prof)

    # 4. Data Quality Summary
    quality_summary = {
        "total_missing_values": total_missing_values,
        "columns_with_missing_values": columns_with_missing,
        "duplicate_rows": duplicate_row_count,
        "columns_with_all_null_values": columns_with_all_null
    }

    profile = {
        "row_count": row_count,
        "column_count": column_count,
        "duplicate_row_count": duplicate_row_count,
        "duplicate_row_percentage": duplicate_row_percentage,
        "quality": quality_summary,
        "columns": columns_profile
    }

    logger.info(f"Dataset profiling completed successfully for {column_count} columns.")
    return profile


def _profile_numeric(series: pd.Series) -> Optional[Dict[str, Any]]:
    """Calculates numeric statistics (count, mean, median, min, max, std, sum) safely."""
    # Convert series to numeric and filter out inf / nan values
    clean_s = pd.to_numeric(series, errors="coerce").replace([np.inf, -np.inf], np.nan).dropna()
    if len(clean_s) == 0:
        return None

    count_val = int(len(clean_s))
    mean_val = _safe_float(clean_s.mean())
    median_val = _safe_float(clean_s.median())
    min_val = _safe_float(clean_s.min())
    max_val = _safe_float(clean_s.max())
    std_val = _safe_float(clean_s.std()) if count_val > 1 else 0.0
    sum_val = _safe_float(clean_s.sum())

    return {
        "count": count_val,
        "mean": mean_val,
        "median": median_val,
        "min": min_val,
        "max": max_val,
        "std": std_val,
        "sum": sum_val
    }


def _profile_categorical(series: pd.Series, top_n: int = 5) -> List[Dict[str, Any]]:
    """Calculates frequency table for top N categorical values."""
    non_null_s = series.dropna()
    if len(non_null_s) == 0:
        return []

    val_counts = non_null_s.astype(str).value_counts().head(top_n)
    top_list = []
    for val, count in val_counts.items():
        top_list.append({
            "value": str(val),
            "count": int(count)
        })
    return top_list


def _profile_text(series: pd.Series) -> Optional[Dict[str, Any]]:
    """Calculates text length statistics (average_length, minimum_length, maximum_length)."""
    non_null_str = series.dropna().astype(str)
    if len(non_null_str) == 0:
        return None

    lengths = non_null_str.str.len()
    return {
        "average_length": round(float(lengths.mean()), 2),
        "minimum_length": int(lengths.min()),
        "maximum_length": int(lengths.max())
    }


def _profile_date(series: pd.Series) -> Optional[Dict[str, Any]]:
    """Calculates min_date and max_date for date/datetime columns."""
    non_null_s = series.dropna()
    if len(non_null_s) == 0:
        return None

    try:
        parsed_dt = pd.to_datetime(non_null_s, errors="coerce", format="mixed").dropna()
        if len(parsed_dt) == 0:
            return None

        min_dt = parsed_dt.min()
        max_dt = parsed_dt.max()

        min_str = min_dt.isoformat() if hasattr(min_dt, "isoformat") else str(min_dt)
        max_str = max_dt.isoformat() if hasattr(max_dt, "isoformat") else str(max_dt)

        return {
            "min_date": min_str,
            "max_date": max_str
        }
    except Exception:
        return None


def _profile_identifier(series: pd.Series, unique_count: int, non_null_count: int) -> Dict[str, Any]:
    """Calculates identifier uniqueness metrics."""
    duplicate_count = max(0, non_null_count - unique_count)
    uniqueness_ratio = round(unique_count / non_null_count, 4) if non_null_count > 0 else 0.0

    return {
        "unique_count": unique_count,
        "duplicate_count": duplicate_count,
        "uniqueness_ratio": uniqueness_ratio
    }


def _safe_float(val: Any) -> Optional[float]:
    """Helper to ensure float values are non-NaN, non-Inf, and JSON serializable."""
    if val is None or pd.isna(val) or math.isnan(val) or math.isinf(val):
        return None
    return round(float(val), 4)
